services:
  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent
    ports: 
      - "9001:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9100:9100"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_dir }}/portainer/portainer_data:/data"
    command:
      --http-enabled -p:9100

    restart: always