services:
  caddy:
    build: "{{ docker_dir }}/caddy/dockerfile-dns"
    hostname: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "{{ docker_dir }}/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "{{ docker_dir }}/caddy/site:/srv"
      - "{{ docker_dir }}/caddy/caddy_data:/data"
      - "{{ docker_dir }}/caddy/caddy_config:/config"
    env_file:
      - "{{ docker_dir }}/caddy/container-vars.env"

volumes:
  caddy_data:
  caddy_config: