version: '3.5'

services:
  dash:
    hostname: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "3002:3001"
    volumes:
      - /:/mnt/host:ro
    networks:
      - nasdashdot
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_FS_DEVICE_FILTER: sdb
      DASHDOT_FS_VIRTUAL_MOUNTS: /mnt/disk/5ec0f641-1ea1-4c9d-af7f-1a5924780204
      DASHDOT_OVERRIDE_STORAGE_BRANDS: /mnt/disk/5ec0f641-1ea1-4c9d-af7f-1a5924780204=Storage Pool
      DASHDOT_ACCEPT_OOKLA_EULA: true

  homarr:
    networks:
      - nasdashdot

networks:
  nasdashdot:
    name: nasdashdot